// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.9.0
// source: proto/reservation.proto

package api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//查询MBTI请求
type QueryMBTIReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//用户UUID
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *QueryMBTIReq) Reset() {
	*x = QueryMBTIReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_reservation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryMBTIReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryMBTIReq) ProtoMessage() {}

func (x *QueryMBTIReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryMBTIReq.ProtoReflect.Descriptor instead.
func (*QueryMBTIReq) Descriptor() ([]byte, []int) {
	return file_proto_reservation_proto_rawDescGZIP(), []int{0}
}

func (x *QueryMBTIReq) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

//查询MBTI返回
type QueryMBTIResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//MBTI数据
	Data *MBTIResult `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// 是否成功注册
	Success bool `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	// 错误码
	ErrorCode string `protobuf:"bytes,3,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	// 错误详情
	ErrorMsg string `protobuf:"bytes,4,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *QueryMBTIResp) Reset() {
	*x = QueryMBTIResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_reservation_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryMBTIResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryMBTIResp) ProtoMessage() {}

func (x *QueryMBTIResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryMBTIResp.ProtoReflect.Descriptor instead.
func (*QueryMBTIResp) Descriptor() ([]byte, []int) {
	return file_proto_reservation_proto_rawDescGZIP(), []int{1}
}

func (x *QueryMBTIResp) GetData() *MBTIResult {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *QueryMBTIResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *QueryMBTIResp) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *QueryMBTIResp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type MBTIResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//注意力方向（精力来源），外倾
	Extraversion float32 `protobuf:"fixed32,1,opt,name=extraversion,proto3" json:"extraversion,omitempty"`
	//认知方式（如何搜集信息），实感
	Sensing float32 `protobuf:"fixed32,2,opt,name=sensing,proto3" json:"sensing,omitempty"`
	//判断方式（如何做决定），理智
	Thinking float32 `protobuf:"fixed32,3,opt,name=thinking,proto3" json:"thinking,omitempty"`
	//生活方式（如何应对外部世界），判断
	Judging float32 `protobuf:"fixed32,4,opt,name=judging,proto3" json:"judging,omitempty"`
}

func (x *MBTIResult) Reset() {
	*x = MBTIResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_reservation_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MBTIResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MBTIResult) ProtoMessage() {}

func (x *MBTIResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MBTIResult.ProtoReflect.Descriptor instead.
func (*MBTIResult) Descriptor() ([]byte, []int) {
	return file_proto_reservation_proto_rawDescGZIP(), []int{2}
}

func (x *MBTIResult) GetExtraversion() float32 {
	if x != nil {
		return x.Extraversion
	}
	return 0
}

func (x *MBTIResult) GetSensing() float32 {
	if x != nil {
		return x.Sensing
	}
	return 0
}

func (x *MBTIResult) GetThinking() float32 {
	if x != nil {
		return x.Thinking
	}
	return 0
}

func (x *MBTIResult) GetJudging() float32 {
	if x != nil {
		return x.Judging
	}
	return 0
}

type GenerateMBTIReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GenerateMBTIReq) Reset() {
	*x = GenerateMBTIReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_reservation_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateMBTIReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateMBTIReq) ProtoMessage() {}

func (x *GenerateMBTIReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateMBTIReq.ProtoReflect.Descriptor instead.
func (*GenerateMBTIReq) Descriptor() ([]byte, []int) {
	return file_proto_reservation_proto_rawDescGZIP(), []int{3}
}

type GenerateMBTIResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GenerateMBTIResp) Reset() {
	*x = GenerateMBTIResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_reservation_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateMBTIResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateMBTIResp) ProtoMessage() {}

func (x *GenerateMBTIResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateMBTIResp.ProtoReflect.Descriptor instead.
func (*GenerateMBTIResp) Descriptor() ([]byte, []int) {
	return file_proto_reservation_proto_rawDescGZIP(), []int{4}
}

type RegisterReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RegisterReq) Reset() {
	*x = RegisterReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_reservation_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReq) ProtoMessage() {}

func (x *RegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReq.ProtoReflect.Descriptor instead.
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return file_proto_reservation_proto_rawDescGZIP(), []int{5}
}

type RegisterResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 是否成功注册
	Success bool `protobuf:"varint,8,opt,name=success,proto3" json:"success,omitempty"`
	// 错误码
	ErrorCode string `protobuf:"bytes,9,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	// 错误详情
	ErrorMsg string `protobuf:"bytes,10,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *RegisterResp) Reset() {
	*x = RegisterResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_reservation_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResp) ProtoMessage() {}

func (x *RegisterResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResp.ProtoReflect.Descriptor instead.
func (*RegisterResp) Descriptor() ([]byte, []int) {
	return file_proto_reservation_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResp) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *RegisterResp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

//微信登录请求
type WXLoginReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//登录时获取的 code，可通过wx.login获取
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *WXLoginReq) Reset() {
	*x = WXLoginReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_reservation_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WXLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WXLoginReq) ProtoMessage() {}

func (x *WXLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WXLoginReq.ProtoReflect.Descriptor instead.
func (*WXLoginReq) Descriptor() ([]byte, []int) {
	return file_proto_reservation_proto_rawDescGZIP(), []int{7}
}

func (x *WXLoginReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

//微信登录返回
type WXLoginResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *WXLoginResp_Data `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// 是否成功访问
	Success bool `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	// 错误码
	ErrorCode string `protobuf:"bytes,3,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	// 错误详情
	ErrorMsg string `protobuf:"bytes,4,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *WXLoginResp) Reset() {
	*x = WXLoginResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_reservation_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WXLoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WXLoginResp) ProtoMessage() {}

func (x *WXLoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WXLoginResp.ProtoReflect.Descriptor instead.
func (*WXLoginResp) Descriptor() ([]byte, []int) {
	return file_proto_reservation_proto_rawDescGZIP(), []int{8}
}

func (x *WXLoginResp) GetData() *WXLoginResp_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *WXLoginResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *WXLoginResp) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *WXLoginResp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type QueryOrderListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//用户的uuid
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *QueryOrderListReq) Reset() {
	*x = QueryOrderListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_reservation_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryOrderListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryOrderListReq) ProtoMessage() {}

func (x *QueryOrderListReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryOrderListReq.ProtoReflect.Descriptor instead.
func (*QueryOrderListReq) Descriptor() ([]byte, []int) {
	return file_proto_reservation_proto_rawDescGZIP(), []int{9}
}

func (x *QueryOrderListReq) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type QueryOrderListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//活动列表数据
	Data *QueryOrderListResp_Data `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// 是否成功访问
	Success bool `protobuf:"varint,8,opt,name=success,proto3" json:"success,omitempty"`
	// 错误码
	ErrorCode string `protobuf:"bytes,9,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	// 错误详情
	ErrorMsg string `protobuf:"bytes,10,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *QueryOrderListResp) Reset() {
	*x = QueryOrderListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_reservation_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryOrderListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryOrderListResp) ProtoMessage() {}

func (x *QueryOrderListResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryOrderListResp.ProtoReflect.Descriptor instead.
func (*QueryOrderListResp) Descriptor() ([]byte, []int) {
	return file_proto_reservation_proto_rawDescGZIP(), []int{10}
}

func (x *QueryOrderListResp) GetData() *QueryOrderListResp_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *QueryOrderListResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *QueryOrderListResp) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *QueryOrderListResp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

// GetSystemInfoReq 表示获取系统信息请求.
type GetSystemInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetSystemInfoReq) Reset() {
	*x = GetSystemInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_reservation_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSystemInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemInfoReq) ProtoMessage() {}

func (x *GetSystemInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemInfoReq.ProtoReflect.Descriptor instead.
func (*GetSystemInfoReq) Descriptor() ([]byte, []int) {
	return file_proto_reservation_proto_rawDescGZIP(), []int{11}
}

// GetSystemInfoResp 表示获取系统信息响应.
type GetSystemInfoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 已使用磁盘空间总数, 单位兆字节.
	TotalUsedMb int64 `protobuf:"varint,1,opt,name=totalUsedMb,proto3" json:"totalUsedMb,omitempty"`
	// 磁盘空间容量总数, 单位兆字节.
	TotalMb int64 `protobuf:"varint,2,opt,name=totalMb,proto3" json:"totalMb,omitempty"`
	// 可用磁盘容量, 单位兆字节.
	AvailableMb int64 `protobuf:"varint,3,opt,name=availableMb,proto3" json:"availableMb,omitempty"`
	// 是否成功访问
	Success bool `protobuf:"varint,8,opt,name=success,proto3" json:"success,omitempty"`
	// 错误码
	ErrorCode string `protobuf:"bytes,9,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	// 错误详情
	ErrorMsg string `protobuf:"bytes,10,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *GetSystemInfoResp) Reset() {
	*x = GetSystemInfoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_reservation_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSystemInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemInfoResp) ProtoMessage() {}

func (x *GetSystemInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemInfoResp.ProtoReflect.Descriptor instead.
func (*GetSystemInfoResp) Descriptor() ([]byte, []int) {
	return file_proto_reservation_proto_rawDescGZIP(), []int{12}
}

func (x *GetSystemInfoResp) GetTotalUsedMb() int64 {
	if x != nil {
		return x.TotalUsedMb
	}
	return 0
}

func (x *GetSystemInfoResp) GetTotalMb() int64 {
	if x != nil {
		return x.TotalMb
	}
	return 0
}

func (x *GetSystemInfoResp) GetAvailableMb() int64 {
	if x != nil {
		return x.AvailableMb
	}
	return 0
}

func (x *GetSystemInfoResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetSystemInfoResp) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *GetSystemInfoResp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

// 获取某一天的可参加的活动列表请求
type QueryActivityListByDayReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//日期，格式为 "20221226"
	Day string `protobuf:"bytes,1,opt,name=day,proto3" json:"day,omitempty"`
	// 本次请求结果实际页码, 一般与请求参数一致
	PageNum int32 `protobuf:"varint,2,opt,name=pageNum,proto3" json:"pageNum,omitempty"`
	// 分页大小
	PageSize int32 `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
}

func (x *QueryActivityListByDayReq) Reset() {
	*x = QueryActivityListByDayReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_reservation_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryActivityListByDayReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryActivityListByDayReq) ProtoMessage() {}

func (x *QueryActivityListByDayReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryActivityListByDayReq.ProtoReflect.Descriptor instead.
func (*QueryActivityListByDayReq) Descriptor() ([]byte, []int) {
	return file_proto_reservation_proto_rawDescGZIP(), []int{13}
}

func (x *QueryActivityListByDayReq) GetDay() string {
	if x != nil {
		return x.Day
	}
	return ""
}

func (x *QueryActivityListByDayReq) GetPageNum() int32 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *QueryActivityListByDayReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 获取某一天的可参加的活动列表返回
type QueryActivityListByDayResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//活动列表数据
	Data *QueryActivityListByDayResp_Data `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// 是否成功访问
	Success bool `protobuf:"varint,8,opt,name=success,proto3" json:"success,omitempty"`
	// 错误码
	ErrorCode string `protobuf:"bytes,9,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	// 错误详情
	ErrorMsg string `protobuf:"bytes,10,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *QueryActivityListByDayResp) Reset() {
	*x = QueryActivityListByDayResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_reservation_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryActivityListByDayResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryActivityListByDayResp) ProtoMessage() {}

func (x *QueryActivityListByDayResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryActivityListByDayResp.ProtoReflect.Descriptor instead.
func (*QueryActivityListByDayResp) Descriptor() ([]byte, []int) {
	return file_proto_reservation_proto_rawDescGZIP(), []int{14}
}

func (x *QueryActivityListByDayResp) GetData() *QueryActivityListByDayResp_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *QueryActivityListByDayResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *QueryActivityListByDayResp) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *QueryActivityListByDayResp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

// 获取全部可参加的活动列表请求
type QueryActivityListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *QueryActivityListReq) Reset() {
	*x = QueryActivityListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_reservation_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryActivityListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryActivityListReq) ProtoMessage() {}

func (x *QueryActivityListReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryActivityListReq.ProtoReflect.Descriptor instead.
func (*QueryActivityListReq) Descriptor() ([]byte, []int) {
	return file_proto_reservation_proto_rawDescGZIP(), []int{15}
}

// 获取全部可参加的活动列表返回
type QueryActivityListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//活动列表数据
	Data *QueryActivityListResp_Data `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// 是否成功访问
	Success bool `protobuf:"varint,8,opt,name=success,proto3" json:"success,omitempty"`
	// 错误码
	ErrorCode string `protobuf:"bytes,9,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	// 错误详情
	ErrorMsg string `protobuf:"bytes,10,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *QueryActivityListResp) Reset() {
	*x = QueryActivityListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_reservation_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryActivityListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryActivityListResp) ProtoMessage() {}

func (x *QueryActivityListResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryActivityListResp.ProtoReflect.Descriptor instead.
func (*QueryActivityListResp) Descriptor() ([]byte, []int) {
	return file_proto_reservation_proto_rawDescGZIP(), []int{16}
}

func (x *QueryActivityListResp) GetData() *QueryActivityListResp_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *QueryActivityListResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *QueryActivityListResp) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *QueryActivityListResp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

//活动详情
type Activity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//名称
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	//价格
	Price float32 `protobuf:"fixed32,2,opt,name=price,proto3" json:"price,omitempty"`
	//时间戳
	Timestamp int64 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	//
	Location string `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	//小图
	SmallImg string `protobuf:"bytes,5,opt,name=small_img,json=smallImg,proto3" json:"small_img,omitempty"`
	// 大图
	BigImg string `protobuf:"bytes,6,opt,name=big_img,json=bigImg,proto3" json:"big_img,omitempty"`
	//描述
	Description string `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	//活动序列号
	ActivitySerial string `protobuf:"bytes,8,opt,name=activitySerial,proto3" json:"activitySerial,omitempty"`
}

func (x *Activity) Reset() {
	*x = Activity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_reservation_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Activity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Activity) ProtoMessage() {}

func (x *Activity) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Activity.ProtoReflect.Descriptor instead.
func (*Activity) Descriptor() ([]byte, []int) {
	return file_proto_reservation_proto_rawDescGZIP(), []int{17}
}

func (x *Activity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Activity) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Activity) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Activity) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Activity) GetSmallImg() string {
	if x != nil {
		return x.SmallImg
	}
	return ""
}

func (x *Activity) GetBigImg() string {
	if x != nil {
		return x.BigImg
	}
	return ""
}

func (x *Activity) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Activity) GetActivitySerial() string {
	if x != nil {
		return x.ActivitySerial
	}
	return ""
}

//订单
type Order struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//序列号
	OrderSerial string `protobuf:"bytes,1,opt,name=orderSerial,proto3" json:"orderSerial,omitempty"`
	//关联的活动序列号
	ActivitySerial string `protobuf:"bytes,2,opt,name=activitySerial,proto3" json:"activitySerial,omitempty"`
	//时间戳
	Timestamp int64 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	//状态。分为待付款，已付款，已退款
	Status string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *Order) Reset() {
	*x = Order{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_reservation_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_proto_reservation_proto_rawDescGZIP(), []int{18}
}

func (x *Order) GetOrderSerial() string {
	if x != nil {
		return x.OrderSerial
	}
	return ""
}

func (x *Order) GetActivitySerial() string {
	if x != nil {
		return x.ActivitySerial
	}
	return ""
}

func (x *Order) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Order) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type WXLoginResp_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//用户唯一标识
	OpenId string `protobuf:"bytes,1,opt,name=openId,proto3" json:"openId,omitempty"`
	//会话密钥
	SessionKey string `protobuf:"bytes,2,opt,name=sessionKey,proto3" json:"sessionKey,omitempty"`
	//用户在开放平台的唯一标识符，若当前小程序已绑定到微信开放平台帐号下会返回，详见 UnionID 机制说明。
	UnionId string `protobuf:"bytes,3,opt,name=unionId,proto3" json:"unionId,omitempty"`
}

func (x *WXLoginResp_Data) Reset() {
	*x = WXLoginResp_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_reservation_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WXLoginResp_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WXLoginResp_Data) ProtoMessage() {}

func (x *WXLoginResp_Data) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WXLoginResp_Data.ProtoReflect.Descriptor instead.
func (*WXLoginResp_Data) Descriptor() ([]byte, []int) {
	return file_proto_reservation_proto_rawDescGZIP(), []int{8, 0}
}

func (x *WXLoginResp_Data) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *WXLoginResp_Data) GetSessionKey() string {
	if x != nil {
		return x.SessionKey
	}
	return ""
}

func (x *WXLoginResp_Data) GetUnionId() string {
	if x != nil {
		return x.UnionId
	}
	return ""
}

//活动列表数据
type QueryOrderListResp_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 当前页记录数
	Size int32 `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	// 总页数
	Pages int32 `protobuf:"varint,2,opt,name=pages,proto3" json:"pages,omitempty"`
	// 本次请求结果实际页码, 一般与请求参数一致
	PageNum int32 `protobuf:"varint,3,opt,name=pageNum,proto3" json:"pageNum,omitempty"`
	// 分页大小
	PageSize  int32    `protobuf:"varint,4,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	OrderList []*Order `protobuf:"bytes,5,rep,name=orderList,proto3" json:"orderList,omitempty"`
	// 查询命中的对象总数, 请求参数trackTotalHits为真时生效, 否则返回-1
	Total int32 `protobuf:"varint,6,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *QueryOrderListResp_Data) Reset() {
	*x = QueryOrderListResp_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_reservation_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryOrderListResp_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryOrderListResp_Data) ProtoMessage() {}

func (x *QueryOrderListResp_Data) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryOrderListResp_Data.ProtoReflect.Descriptor instead.
func (*QueryOrderListResp_Data) Descriptor() ([]byte, []int) {
	return file_proto_reservation_proto_rawDescGZIP(), []int{10, 0}
}

func (x *QueryOrderListResp_Data) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *QueryOrderListResp_Data) GetPages() int32 {
	if x != nil {
		return x.Pages
	}
	return 0
}

func (x *QueryOrderListResp_Data) GetPageNum() int32 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *QueryOrderListResp_Data) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *QueryOrderListResp_Data) GetOrderList() []*Order {
	if x != nil {
		return x.OrderList
	}
	return nil
}

func (x *QueryOrderListResp_Data) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

//活动列表数据
type QueryActivityListByDayResp_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 当前页记录数
	Size int32 `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	// 总页数
	Pages int32 `protobuf:"varint,2,opt,name=pages,proto3" json:"pages,omitempty"`
	// 本次请求结果实际页码, 一般与请求参数一致
	PageNum int32 `protobuf:"varint,3,opt,name=pageNum,proto3" json:"pageNum,omitempty"`
	// 分页大小
	PageSize int32 `protobuf:"varint,4,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	// 活动列表
	ActivityList []*Activity `protobuf:"bytes,5,rep,name=activityList,proto3" json:"activityList,omitempty"`
	// 查询命中的对象总数, 请求参数trackTotalHits为真时生效, 否则返回-1
	Total int32 `protobuf:"varint,6,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *QueryActivityListByDayResp_Data) Reset() {
	*x = QueryActivityListByDayResp_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_reservation_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryActivityListByDayResp_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryActivityListByDayResp_Data) ProtoMessage() {}

func (x *QueryActivityListByDayResp_Data) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryActivityListByDayResp_Data.ProtoReflect.Descriptor instead.
func (*QueryActivityListByDayResp_Data) Descriptor() ([]byte, []int) {
	return file_proto_reservation_proto_rawDescGZIP(), []int{14, 0}
}

func (x *QueryActivityListByDayResp_Data) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *QueryActivityListByDayResp_Data) GetPages() int32 {
	if x != nil {
		return x.Pages
	}
	return 0
}

func (x *QueryActivityListByDayResp_Data) GetPageNum() int32 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *QueryActivityListByDayResp_Data) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *QueryActivityListByDayResp_Data) GetActivityList() []*Activity {
	if x != nil {
		return x.ActivityList
	}
	return nil
}

func (x *QueryActivityListByDayResp_Data) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

//活动列表数据
type QueryActivityListResp_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 当前页记录数
	Size int32 `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	// 总页数
	Pages int32 `protobuf:"varint,2,opt,name=pages,proto3" json:"pages,omitempty"`
	// 本次请求结果实际页码, 一般与请求参数一致
	PageNum int32 `protobuf:"varint,3,opt,name=pageNum,proto3" json:"pageNum,omitempty"`
	// 分页大小
	PageSize int32 `protobuf:"varint,4,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	// 活动列表
	ActivityList []*Activity `protobuf:"bytes,5,rep,name=activityList,proto3" json:"activityList,omitempty"`
	// 查询命中的对象总数, 请求参数trackTotalHits为真时生效, 否则返回-1
	Total int32 `protobuf:"varint,6,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *QueryActivityListResp_Data) Reset() {
	*x = QueryActivityListResp_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_reservation_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryActivityListResp_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryActivityListResp_Data) ProtoMessage() {}

func (x *QueryActivityListResp_Data) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryActivityListResp_Data.ProtoReflect.Descriptor instead.
func (*QueryActivityListResp_Data) Descriptor() ([]byte, []int) {
	return file_proto_reservation_proto_rawDescGZIP(), []int{16, 0}
}

func (x *QueryActivityListResp_Data) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *QueryActivityListResp_Data) GetPages() int32 {
	if x != nil {
		return x.Pages
	}
	return 0
}

func (x *QueryActivityListResp_Data) GetPageNum() int32 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *QueryActivityListResp_Data) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *QueryActivityListResp_Data) GetActivityList() []*Activity {
	if x != nil {
		return x.ActivityList
	}
	return nil
}

func (x *QueryActivityListResp_Data) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_proto_reservation_proto protoreflect.FileDescriptor

var file_proto_reservation_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x72, 0x65, 0x73, 0x65, 0x72,
	0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x22, 0x0a, 0x0c, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4d, 0x42, 0x54,
	0x49, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x22, 0x90, 0x01, 0x0a, 0x0d, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x4d, 0x42, 0x54, 0x49, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2b, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x72, 0x65, 0x73, 0x65, 0x72,
	0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4d, 0x42, 0x54, 0x49, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x22, 0x80, 0x01, 0x0a, 0x0a,
	0x4d, 0x42, 0x54, 0x49, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x65, 0x78,
	0x74, 0x72, 0x61, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x0c, 0x65, 0x78, 0x74, 0x72, 0x61, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x65, 0x6e, 0x73, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x07, 0x73, 0x65, 0x6e, 0x73, 0x69, 0x6e, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x68, 0x69, 0x6e,
	0x6b, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x74, 0x68, 0x69, 0x6e,
	0x6b, 0x69, 0x6e, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x6a, 0x75, 0x64, 0x67, 0x69, 0x6e, 0x67, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x6a, 0x75, 0x64, 0x67, 0x69, 0x6e, 0x67, 0x22, 0x11,
	0x0a, 0x0f, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4d, 0x42, 0x54, 0x49, 0x52, 0x65,
	0x71, 0x22, 0x12, 0x0a, 0x10, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4d, 0x42, 0x54,
	0x49, 0x52, 0x65, 0x73, 0x70, 0x22, 0x0d, 0x0a, 0x0b, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x22, 0x62, 0x0a, 0x0c, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x1c,
	0x0a, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x22, 0x20, 0x0a, 0x0a, 0x57, 0x58, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0xee, 0x01, 0x0a, 0x0b, 0x57,
	0x58, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x31, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x72, 0x65, 0x73, 0x65, 0x72,
	0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x57, 0x58, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x43, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73,
	0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73,
	0x67, 0x1a, 0x58, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x70, 0x65,
	0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x70, 0x65, 0x6e, 0x49,
	0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4b, 0x65, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4b, 0x65,
	0x79, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x6e, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x75, 0x6e, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x27, 0x0a, 0x11, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x75, 0x75, 0x69, 0x64, 0x22, 0xd3, 0x02, 0x0a, 0x12, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x38, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x72, 0x65, 0x73, 0x65,
	0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12,
	0x1c, 0x0a, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x1a, 0xae, 0x01, 0x0a, 0x04, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x61, 0x67, 0x65, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x70, 0x61, 0x67, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x70, 0x61, 0x67, 0x65, 0x4e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x70,
	0x61, 0x67, 0x65, 0x4e, 0x75, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69,
	0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69,
	0x7a, 0x65, 0x12, 0x30, 0x0a, 0x09, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x18,
	0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x09, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x12, 0x0a, 0x10, 0x47, 0x65,
	0x74, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x22, 0xc5,
	0x01, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x55, 0x73, 0x65,
	0x64, 0x4d, 0x62, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x55, 0x73, 0x65, 0x64, 0x4d, 0x62, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x4d,
	0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x4d, 0x62,
	0x12, 0x20, 0x0a, 0x0b, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x4d, 0x62, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65,
	0x4d, 0x62, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x1c, 0x0a, 0x09,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x22, 0x63, 0x0a, 0x19, 0x51, 0x75, 0x65, 0x72, 0x79, 0x41,
	0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x79, 0x44, 0x61, 0x79,
	0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x61, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x64, 0x61, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x67, 0x65, 0x4e, 0x75, 0x6d,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x70, 0x61, 0x67, 0x65, 0x4e, 0x75, 0x6d, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0xec, 0x02, 0x0a, 0x1a,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x4c, 0x69, 0x73,
	0x74, 0x42, 0x79, 0x44, 0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x40, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x72, 0x65, 0x73, 0x65, 0x72,
	0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x41, 0x63, 0x74, 0x69,
	0x76, 0x69, 0x74, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x79, 0x44, 0x61, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43,
	0x6f, 0x64, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67,
	0x1a, 0xb7, 0x01, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x70, 0x61, 0x67, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x70, 0x61,
	0x67, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x67, 0x65, 0x4e, 0x75, 0x6d, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x70, 0x61, 0x67, 0x65, 0x4e, 0x75, 0x6d, 0x12, 0x1a, 0x0a,
	0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x39, 0x0a, 0x0c, 0x61, 0x63, 0x74,
	0x69, 0x76, 0x69, 0x74, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x41, 0x63,
	0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x52, 0x0c, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x16, 0x0a, 0x14, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x22, 0xe2, 0x02, 0x0a, 0x15, 0x51, 0x75, 0x65, 0x72, 0x79, 0x41, 0x63, 0x74, 0x69,
	0x76, 0x69, 0x74, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3b, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x72, 0x65, 0x73,
	0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x41, 0x63,
	0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x1a, 0xb7, 0x01,
	0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x61,
	0x67, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x70, 0x61, 0x67, 0x65, 0x73,
	0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x67, 0x65, 0x4e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x70, 0x61, 0x67, 0x65, 0x4e, 0x75, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61,
	0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61,
	0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x39, 0x0a, 0x0c, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69,
	0x74, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x72,
	0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x76,
	0x69, 0x74, 0x79, 0x52, 0x0c, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0xee, 0x01, 0x0a, 0x08, 0x41, 0x63, 0x74, 0x69,
	0x76, 0x69, 0x74, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1a, 0x0a, 0x08,
	0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x6d, 0x61, 0x6c,
	0x6c, 0x5f, 0x69, 0x6d, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x6d, 0x61,
	0x6c, 0x6c, 0x49, 0x6d, 0x67, 0x12, 0x17, 0x0a, 0x07, 0x62, 0x69, 0x67, 0x5f, 0x69, 0x6d, 0x67,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x69, 0x67, 0x49, 0x6d, 0x67, 0x12, 0x20,
	0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x26, 0x0a, 0x0e, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x53, 0x65, 0x72, 0x69,
	0x61, 0x6c, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69,
	0x74, 0x79, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x22, 0x87, 0x01, 0x0a, 0x05, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x65, 0x72, 0x69, 0x61,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x65,
	0x72, 0x69, 0x61, 0x6c, 0x12, 0x26, 0x0a, 0x0e, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79,
	0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x61, 0x63,
	0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x12, 0x1c, 0x0a, 0x09,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x32, 0xfd, 0x06, 0x0a, 0x12, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x6b, 0x0a, 0x0d, 0x47, 0x65, 0x74,
	0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1d, 0x2e, 0x72, 0x65, 0x73,
	0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x79, 0x73, 0x74,
	0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x1e, 0x2e, 0x72, 0x65, 0x73, 0x65,
	0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x79, 0x73, 0x74, 0x65,
	0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x22, 0x1b, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x15, 0x12, 0x13, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x65, 0x74, 0x5f, 0x73, 0x79, 0x73, 0x74, 0x65,
	0x6d, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x5d, 0x0a, 0x08, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x12, 0x18, 0x2e, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x72,
	0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x22, 0x1c, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x16, 0x22,
	0x11, 0x2f, 0x76, 0x31, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x3a, 0x01, 0x2a, 0x12, 0x5a, 0x0a, 0x07, 0x57, 0x58, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x12, 0x17, 0x2e, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x57,
	0x58, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x72, 0x65, 0x73, 0x65,
	0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x57, 0x58, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x22, 0x1c, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x16, 0x22, 0x11, 0x2f, 0x76, 0x31,
	0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x77, 0x78, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x3a, 0x01,
	0x2a, 0x12, 0x6e, 0x0a, 0x0c, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4d, 0x42, 0x54,
	0x49, 0x12, 0x1c, 0x2e, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4d, 0x42, 0x54, 0x49, 0x52, 0x65, 0x71, 0x1a,
	0x1d, 0x2e, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x47, 0x65,
	0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4d, 0x42, 0x54, 0x49, 0x52, 0x65, 0x73, 0x70, 0x22, 0x21,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1b, 0x22, 0x16, 0x2f, 0x76, 0x31, 0x2f, 0x75, 0x73, 0x65, 0x72,
	0x2f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x5f, 0x6d, 0x62, 0x74, 0x69, 0x3a, 0x01,
	0x2a, 0x12, 0x44, 0x0a, 0x09, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4d, 0x42, 0x54, 0x49, 0x12, 0x19,
	0x2e, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x4d, 0x42, 0x54, 0x49, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x72, 0x65, 0x73, 0x65,
	0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4d, 0x42, 0x54,
	0x49, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x72, 0x0a, 0x0e, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1e, 0x2e, 0x72, 0x65, 0x73, 0x65,
	0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x1f, 0x2e, 0x72, 0x65, 0x73, 0x65,
	0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x22, 0x1f, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x19, 0x22, 0x14, 0x2f, 0x76, 0x31, 0x2f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2f, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x3a, 0x01, 0x2a, 0x12, 0x7e, 0x0a, 0x11, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x21, 0x2e, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x1a, 0x22, 0x2e, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x22, 0x22, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1c, 0x22,
	0x17, 0x2f, 0x76, 0x31, 0x2f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2f, 0x61, 0x63, 0x74, 0x69, 0x76,
	0x69, 0x74, 0x79, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x3a, 0x01, 0x2a, 0x12, 0x94, 0x01, 0x0a, 0x16,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x4c, 0x69, 0x73,
	0x74, 0x42, 0x79, 0x44, 0x61, 0x79, 0x12, 0x26, 0x2e, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69,
	0x74, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x79, 0x44, 0x61, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x27,
	0x2e, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x79,
	0x44, 0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x22, 0x29, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x23, 0x22,
	0x1e, 0x2f, 0x76, 0x31, 0x2f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2f, 0x61, 0x63, 0x74, 0x69, 0x76,
	0x69, 0x74, 0x79, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x62, 0x79, 0x5f, 0x64, 0x61, 0x79, 0x3a,
	0x01, 0x2a, 0x42, 0x1c, 0x5a, 0x1a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x61, 0x70, 0x69,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_reservation_proto_rawDescOnce sync.Once
	file_proto_reservation_proto_rawDescData = file_proto_reservation_proto_rawDesc
)

func file_proto_reservation_proto_rawDescGZIP() []byte {
	file_proto_reservation_proto_rawDescOnce.Do(func() {
		file_proto_reservation_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_reservation_proto_rawDescData)
	})
	return file_proto_reservation_proto_rawDescData
}

var file_proto_reservation_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_proto_reservation_proto_goTypes = []interface{}{
	(*QueryMBTIReq)(nil),                    // 0: reservation.QueryMBTIReq
	(*QueryMBTIResp)(nil),                   // 1: reservation.QueryMBTIResp
	(*MBTIResult)(nil),                      // 2: reservation.MBTIResult
	(*GenerateMBTIReq)(nil),                 // 3: reservation.GenerateMBTIReq
	(*GenerateMBTIResp)(nil),                // 4: reservation.GenerateMBTIResp
	(*RegisterReq)(nil),                     // 5: reservation.RegisterReq
	(*RegisterResp)(nil),                    // 6: reservation.RegisterResp
	(*WXLoginReq)(nil),                      // 7: reservation.WXLoginReq
	(*WXLoginResp)(nil),                     // 8: reservation.WXLoginResp
	(*QueryOrderListReq)(nil),               // 9: reservation.QueryOrderListReq
	(*QueryOrderListResp)(nil),              // 10: reservation.QueryOrderListResp
	(*GetSystemInfoReq)(nil),                // 11: reservation.GetSystemInfoReq
	(*GetSystemInfoResp)(nil),               // 12: reservation.GetSystemInfoResp
	(*QueryActivityListByDayReq)(nil),       // 13: reservation.QueryActivityListByDayReq
	(*QueryActivityListByDayResp)(nil),      // 14: reservation.QueryActivityListByDayResp
	(*QueryActivityListReq)(nil),            // 15: reservation.QueryActivityListReq
	(*QueryActivityListResp)(nil),           // 16: reservation.QueryActivityListResp
	(*Activity)(nil),                        // 17: reservation.Activity
	(*Order)(nil),                           // 18: reservation.Order
	(*WXLoginResp_Data)(nil),                // 19: reservation.WXLoginResp.Data
	(*QueryOrderListResp_Data)(nil),         // 20: reservation.QueryOrderListResp.Data
	(*QueryActivityListByDayResp_Data)(nil), // 21: reservation.QueryActivityListByDayResp.Data
	(*QueryActivityListResp_Data)(nil),      // 22: reservation.QueryActivityListResp.Data
}
var file_proto_reservation_proto_depIdxs = []int32{
	2,  // 0: reservation.QueryMBTIResp.data:type_name -> reservation.MBTIResult
	19, // 1: reservation.WXLoginResp.data:type_name -> reservation.WXLoginResp.Data
	20, // 2: reservation.QueryOrderListResp.data:type_name -> reservation.QueryOrderListResp.Data
	21, // 3: reservation.QueryActivityListByDayResp.data:type_name -> reservation.QueryActivityListByDayResp.Data
	22, // 4: reservation.QueryActivityListResp.data:type_name -> reservation.QueryActivityListResp.Data
	18, // 5: reservation.QueryOrderListResp.Data.orderList:type_name -> reservation.Order
	17, // 6: reservation.QueryActivityListByDayResp.Data.activityList:type_name -> reservation.Activity
	17, // 7: reservation.QueryActivityListResp.Data.activityList:type_name -> reservation.Activity
	11, // 8: reservation.ReservationService.GetSystemInfo:input_type -> reservation.GetSystemInfoReq
	5,  // 9: reservation.ReservationService.Register:input_type -> reservation.RegisterReq
	7,  // 10: reservation.ReservationService.WXLogin:input_type -> reservation.WXLoginReq
	3,  // 11: reservation.ReservationService.GenerateMBTI:input_type -> reservation.GenerateMBTIReq
	0,  // 12: reservation.ReservationService.QueryMBTI:input_type -> reservation.QueryMBTIReq
	9,  // 13: reservation.ReservationService.QueryOrderList:input_type -> reservation.QueryOrderListReq
	15, // 14: reservation.ReservationService.QueryActivityList:input_type -> reservation.QueryActivityListReq
	13, // 15: reservation.ReservationService.QueryActivityListByDay:input_type -> reservation.QueryActivityListByDayReq
	12, // 16: reservation.ReservationService.GetSystemInfo:output_type -> reservation.GetSystemInfoResp
	6,  // 17: reservation.ReservationService.Register:output_type -> reservation.RegisterResp
	8,  // 18: reservation.ReservationService.WXLogin:output_type -> reservation.WXLoginResp
	4,  // 19: reservation.ReservationService.GenerateMBTI:output_type -> reservation.GenerateMBTIResp
	1,  // 20: reservation.ReservationService.QueryMBTI:output_type -> reservation.QueryMBTIResp
	10, // 21: reservation.ReservationService.QueryOrderList:output_type -> reservation.QueryOrderListResp
	16, // 22: reservation.ReservationService.QueryActivityList:output_type -> reservation.QueryActivityListResp
	14, // 23: reservation.ReservationService.QueryActivityListByDay:output_type -> reservation.QueryActivityListByDayResp
	16, // [16:24] is the sub-list for method output_type
	8,  // [8:16] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_reservation_proto_init() }
func file_proto_reservation_proto_init() {
	if File_proto_reservation_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_reservation_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryMBTIReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_reservation_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryMBTIResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_reservation_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MBTIResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_reservation_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateMBTIReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_reservation_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateMBTIResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_reservation_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_reservation_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_reservation_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WXLoginReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_reservation_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WXLoginResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_reservation_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryOrderListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_reservation_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryOrderListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_reservation_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSystemInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_reservation_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSystemInfoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_reservation_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryActivityListByDayReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_reservation_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryActivityListByDayResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_reservation_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryActivityListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_reservation_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryActivityListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_reservation_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Activity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_reservation_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Order); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_reservation_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WXLoginResp_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_reservation_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryOrderListResp_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_reservation_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryActivityListByDayResp_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_reservation_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryActivityListResp_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_reservation_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_reservation_proto_goTypes,
		DependencyIndexes: file_proto_reservation_proto_depIdxs,
		MessageInfos:      file_proto_reservation_proto_msgTypes,
	}.Build()
	File_proto_reservation_proto = out.File
	file_proto_reservation_proto_rawDesc = nil
	file_proto_reservation_proto_goTypes = nil
	file_proto_reservation_proto_depIdxs = nil
}
